project:
  type: website

website:
  title: "Evaluating Musical Predictions with Multiple Versions of a Work"
  description: "Reproducible data, results, and analysis from Swierczek & Schutz, 2025 in Music & Science."
  site-url: "https://konradswierczek.github.io/Evaluating-Musical-Predictions-with-Multiple-Versions-of-a-Work/"
  repo-url: "https://github.com/konradswierczek/Evaluating-Musical-Predictions-with-Multiple-Versions-of-a-Work"

  navbar:
    background: secondary
    logo: https://maplelabs.info/wp-content/uploads/2018/05/final_head-darker-leaf-png-300x300.png
    logo-href: https://maplelab.net
    left:
      - href: index.qmd
        text: Home
      - href: https://swierckj.shinyapps.io/variation-between-versions/
        text: Interactive Data
      - icon: github
        href: https://github.com/konradswierczek/Evaluating-Musical-Predictions-with-Multiple-Versions-of-a-Work
      - icon: book
        href: https://journals.sagepub.com/doi/10.1177/20592043251384138


  page-navigation: true
  back-to-top-navigation: true

  page-footer: 
    right: 
      - icon: browser-chrome
        href: https://konradswierczek.ca
      - icon: envelope
        href: mailto:swierckj@mcmaster.ca
      - icon: github
        href: https://github.com/konradswierczek/Evaluating-Musical-Predictions-with-Multiple-Versions-of-a-Work
      - icon: book
        href: https://journals.sagepub.com/doi/10.1177/20592043251384138
