project:
  type: website

website:
  title: "Musical Feature Evaluation with Versions"
  description: "Description goes here."
  site-url: "https://konradswierczek.github.io/variation-between-versions/"
  repo-url: "https://github.com/konradswierczek/variation-between-versions"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/konradswierczek/variation-between-versions

  page-navigation: true
  back-to-top-navigation: true

  page-footer: 
    right: 
      - icon: github
        href: https://github.com/konradswierczek/
